apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: qlens-istio-production

namespace: quantum-system

commonLabels:
  environment: production

resources:
  - ../../base
  - advanced-security.yaml
  - waf-policies.yaml
  - chaos-engineering.yaml

patchesStrategicMerge:
  - gateway-patch.yaml
  - security-patch.yaml
  - performance-patch.yaml