apiVersion: apps/v1
kind: Deployment
metadata:
  name: qlens-router
  labels:
    app.kubernetes.io/name: qlens-router
    app.kubernetes.io/component: router
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: qlens-router
      app.kubernetes.io/component: router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qlens-router
        app.kubernetes.io/component: router
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8106"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: qlens
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: qlens-router
        image: qlens-router
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8106
          protocol: TCP
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: qlens-config
              key: ENVIRONMENT
        - name: SERVICE_NAME
          value: "qlens-router"
        - name: PORT
          value: "8106"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: qlens-config
              key: LOG_LEVEL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: qlens-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: qlens-secrets
              key: ANTHROPIC_API_KEY
              optional: true
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: qlens-router
  labels:
    app.kubernetes.io/name: qlens-router
    app.kubernetes.io/component: router
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8106"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8106
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: qlens-router
    app.kubernetes.io/component: router