apiVersion: apps/v1
kind: Deployment
metadata:
  name: qlens-gateway
  labels:
    app.kubernetes.io/name: qlens-gateway
    app.kubernetes.io/component: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: qlens-gateway
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qlens-gateway
        app.kubernetes.io/component: gateway
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8105"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: qlens
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: qlens-gateway
        image: qlens-gateway
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8105
          protocol: TCP
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: qlens-config
              key: ENVIRONMENT
        - name: SERVICE_NAME
          value: "qlens-gateway"
        - name: PORT
          value: "8105"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: qlens-config
              key: LOG_LEVEL
        - name: ISTIO_ENABLED
          valueFrom:
            configMapKeyRef:
              name: qlens-config
              key: ISTIO_ENABLED
        - name: AUTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: qlens-config
              key: AUTH_ENABLED
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: qlens-gateway
  labels:
    app.kubernetes.io/name: qlens-gateway
    app.kubernetes.io/component: gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8105"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8105
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: qlens-gateway
    app.kubernetes.io/component: gateway