apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-setup
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: storage-setup
  template:
    metadata:
      labels:
        name: storage-setup
    spec:
      hostPID: true
      containers:
      - name: storage-setup
        image: alpine:latest
        command: 
          - sh
          - -c
          - |
            mkdir -p /host/mnt/k8s-data/{postgresql,redis,nats,qdrant,weaviate,prometheus,grafana}
            chmod 777 /host/mnt/k8s-data/*
            echo "Storage directories created"
            sleep 3600
        volumeMounts:
        - name: host-root
          mountPath: /host
        securityContext:
          privileged: true
      volumes:
      - name: host-root
        hostPath:
          path: /
      nodeSelector:
        kubernetes.io/os: linux