apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"registry-storage","namespace":"image-registry"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-worker-02
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-09-05T01:18:43Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: registry-storage
    namespace: image-registry
    resourceVersion: "692507"
    uid: f6f9e46b-dc8f-4262-83e5-72fe95422752
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-f6f9e46b-dc8f-4262-83e5-72fe95422752
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-09-05T03:30:19Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: packer-builder
    name: docker-storage-packer-builder-0
    namespace: packer-system
    resourceVersion: "725122"
    uid: b3e5431c-5f05-43d1-b15d-2f79dda90029
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-b3e5431c-5f05-43d1-b15d-2f79dda90029
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"qdrant-storage","namespace":"quantumlayer"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-worker
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-09-05T16:35:18Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: qdrant-storage
    namespace: quantumlayer
    resourceVersion: "901364"
    uid: cf7139e8-8170-443b-97ac-c6f92ceae901
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-cf7139e8-8170-443b-97ac-c6f92ceae901
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-09-03T04:45:13Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/name: postgresql
    name: data-postgres-postgresql-0
    namespace: temporal
    resourceVersion: "69946"
    uid: 66fec077-edc4-4fbf-93d4-e6d5dfc349c6
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-66fec077-edc4-4fbf-93d4-e6d5dfc349c6
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-09-03T04:48:23Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/name: alertmanager
    name: storage-temporal-alertmanager-0
    namespace: temporal
    resourceVersion: "71122"
    uid: 2302c991-f8da-4bcc-a310-156f494b0ccb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-2302c991-f8da-4bcc-a310-156f494b0ccb
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
