apiVersion: v1
items:
- apiVersion: v1
  data:
    severity-levels: |
      critical: 9.0-10.0
      high: 7.0-8.9
      medium: 4.0-6.9
      low: 0.0-3.9
    sources: |
      nvd: https://services.nvd.nist.gov/rest/json/cves/2.0
      mitre: https://cve.mitre.org/data/downloads
      github: https://api.github.com/security-advisories
    sync-config: |
      interval: 6h
      batch_size: 100
      max_retries: 3
      timeout: 30s
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"severity-levels":"critical: 9.0-10.0\nhigh: 7.0-8.9\nmedium: 4.0-6.9\nlow: 0.0-3.9\n","sources":"nvd: https://services.nvd.nist.gov/rest/json/cves/2.0\nmitre: https://cve.mitre.org/data/downloads\ngithub: https://api.github.com/security-advisories\n","sync-config":"interval: 6h\nbatch_size: 100\nmax_retries: 3\ntimeout: 30s\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cve-tracker-config","namespace":"security-services"}}
    creationTimestamp: "2025-09-05T03:52:20Z"
    name: cve-tracker-config
    namespace: security-services
    resourceVersion: "730412"
    uid: 784f2212-b1b7-41f9-a659-3d6acb33dfda
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIMMYq2AaEuqAwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTA5MDIyMzA0MzJaFw0zNTA4MzEyMzA5MzJaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDQZPTv1qUWMYzMd+82eZZkoQzofbS+FOUCnqcmFmagGMaOuWqHit1NX5KE
      GjDS0DBI0sTk0GiRPLPsNoehZexKRC0xsN9RVsE2gEj75pT7oLvP1BxbFI9/X5gv
      wQY8z6IJ3ORA8iND99pL6Re1MATiA7CJW/3kdwZgo93+mhirLRTolvFsg/b7kH1v
      SJ+GqSQB5Jr5EpGZ1PLoeJuR7pTNEuD74KRSmhu1hM6RubDefS2aG4j1zZILHKDf
      uzxYHm99XNzkGxeDFd3TLcUyYk7qutfurAapoCXaGuQxdG7wI1IlHx1WRArDCGvB
      Z+1DyLYlXrJBiCO2P4maMi41BLe3AgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBStBvTyw8p/O+SZtwZdO4Di7BTSvjAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB8zOG/3K9d
      nZpNeciU+jxRs8mi2KyNrBN5tVvHzRghPUewIRJuKTe/0o12sGTZwFQNaqu1I+zR
      uZe4hVB7VljKfXlpTFWv+CQZztOOgodQdkGzHgl1hxEkTCEO9koTqTf32AbUjmCv
      8Lla3rJh77N1Mh8lIfOWebWM4OhaYRAKo/6/Vmc02JMuR4+x+vblcI6pmTQlHPjl
      i5m0DvFaRp+xLPDujuAm0lhCejRyXB6Y5BhAGFH3DBUuCCytDcZCyINe1pfz3jux
      OZz6hTCT2iAR2ceDb0BqVfD5R5GSg7I5xtXHzFhEYdWAObulsLjrcrGjTljVw6Aj
      pvYaGh0uEzDb
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-09-05T03:52:20Z"
    name: kube-root-ca.crt
    namespace: security-services
    resourceVersion: "730391"
    uid: 3e9ee1a4-71a0-41c1-9338-4256c7982851
kind: List
metadata:
  resourceVersion: ""
