apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: qlens-istio-staging

namespace: quantum-system

commonLabels:
  environment: staging

resources:
  - ../../base
  - rate-limiting.yaml
  - canary-deployment.yaml

patchesStrategicMerge:
  - gateway-patch.yaml
  - security-patch.yaml